plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "spec/**/*"
    - "lib/tasks/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 18
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 6


Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

Layout/LineLength:
  Max: 140

RSpec/ExampleLength:
  Exclude:
    - "spec/**/*"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/**/*"

RSpec/StubbedMock:
  Exclude:
    - "spec/**/*"

RSpec/MessageSpies:
  Exclude:
    - "spec/**/*"

RSpec/NoExpectationExample:
  Exclude:
    - "spec/**/*"

RSpec/SubjectStub:
  Exclude:
    - "spec/**/*"

RSpec/PendingWithoutReason:
  Exclude:
    - "spec/**/*"

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/**/*"

RSpec/ContextWording:
  Exclude:
    - "spec/**/*"
