# Buildkite pipeline for coverage-reporter
# This pipeline runs RuboCop and the RSpec test suite across multiple Ruby versions.
# It uses Docker images for consistent Ruby environments.
#
# Parallelization:
# Each RSpec step now uses Buildkite parallelism to split the spec files across
# multiple parallel jobs (default 4). The splitting logic deterministically
# partitions the sorted list of *_spec.rb files. Jobs with no assigned files
# exit successfully (useful when specs < parallelism).
#
# If you add or remove supported Rubies, update the list below to match
# the GitHub Actions matrix (.github/workflows/ci.yml).

env:
  # Fail fast if any command in a pipeline fails
  SHELLOPTS: errexit:pipefail

steps:
  # ----------------------------------------
  # Lint
  # ----------------------------------------
  - label: ":rubocop: RuboCop"
    key: rubocop
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.3" # Use a recent stable Ruby for linting
          shell: ["/bin/bash", "-e", "-c"]
    commands:
      - bundle config set path 'vendor/bundle'
      - bundle install --jobs=4 --retry=3
      - bundle exec rubocop

  - wait

  # ----------------------------------------
  # RSpec test matrix (parallelized)
  # ----------------------------------------

  - label: ":rspec: Ruby 3.4"
    key: rspec
    parallelism: 4
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.4"
          propagate-environment: true
          environment:
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
            - BUILDKITE_JOB_ID
          shell: ["/bin/bash", "-e", "-c"]
    command: .buildkite/script/test
    artifact_paths:
      - "coverage/resultset-*.json"

  - label: ":package: Download coverage artifacts"
    depends_on: rspec
    key: merge-coverage
    commands:
      - mkdir -p coverage
      - buildkite-agent artifact download "coverage/resultset-*.json" coverage/
      - bundle config set path 'vendor/bundle'
      - bundle install --jobs=4 --retry=3
      - bundle exec rake coverage:merge
