env:
  # Fail fast if any command in a pipeline fails
  SHELLOPTS: errexit:pipefail

steps:
  # ----------------------------------------
  # Lint
  # ----------------------------------------
  - label: ":rubocop: RuboCop"
    key: rubocop
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.4" # Use a recent stable Ruby for linting
          shell: ["/bin/bash", "-e", "-c"]
    commands:
      - bundle config set path 'vendor/bundle'
      - bundle install --jobs=4 --retry=3
      - bundle exec rubocop

  - wait

  # ----------------------------------------
  # RSpec test matrix (parallelized)
  # ----------------------------------------

  - label: ":rspec: Ruby 3.4"
    key: rspec
    parallelism: 4
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.4"
          propagate-environment: true
          environment:
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
          shell: ["/bin/bash", "-e", "-c"]
    command: .buildkite/script/test
    artifact_paths:
      - "coverage/resultset-*.json"

  - label: ":package: Collate coverage reports"
    depends_on: rspec
    key: merge-coverage
    plugins:
      - artifacts#v1.9.4:
          download: "coverage/resultset-*.json"
      - docker#v5.11.0:
          image: "ruby:3.4"
          mount-buildkite-agent: true
          propagate-environment: true
          shell: ["/bin/bash", "-e", "-c"]
    command: .buildkite/script/collate
    artifact_paths:
      - "coverage/index.html"
      - "coverage/assets.tar.gz"
      - "coverage/coverage.json"

  - label: "Report coverage to GitHub"
    depends_on: merge-coverage
    key: report-coverage
    plugins:
      - artifacts#v1.9.4:
          download: "coverage/coverage.json"
      - docker#v5.11.0:
          image: "ruby:3.4"
          mount-buildkite-agent: true
          propagate-environment: true
          shell: ["/bin/bash", "-e", "-c"]
    command: .buildkite/script/report