#!/bin/sh

bundle config set path 'vendor/bundle'
gem build coverage-reporter.gemspec
gem install coverage-reporter-*.gem

export REPORT_URL=$(ruby .buildkite/build_report_url.rb)

coverage-reporter report
